const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, curr) => acc + curr, 0);  
const isEven = num => num % 2 === 0;  
const evenNumbers = numbers.filter(isEven);  
const square = num => num ** 2;  
const squaredNumbers = numbers.map(square);  
console.log('Doubled:', doubled);  
console.log('Sum:', sum);  
console.log('Even Numbers:', evenNumbers);
